version: '2'
services:
  seed:
    container_name: akka-sample-cluster-docker-compose-java_seed_1
    image: lightbend/akka-sample-cluster-docker-compose-java:latest
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN

    ports:
      - '1600:1600'
      - '127.0.0.1:10051:10051'
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      LISTEN_TCP_PORT : 10051
      SEED_PORT_1600_TCP_ADDR: seed
  c1:
    image: lightbend/akka-sample-cluster-docker-compose-java:latest
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - '1601:1601'
      - '127.0.0.1:10056:10056'
    environment:
      CLUSTER_PORT: 1601
      CLUSTER_IP: c1
      LISTEN_TCP_PORT : 10056
      SEED_PORT_1600_TCP_ADDR: seed
  c2:
    image: lightbend/akka-sample-cluster-docker-compose-java:latest
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - '1602:1602'
      - '127.0.0.1:10057:10057'
    environment:
      CLUSTER_PORT: 1602
      CLUSTER_IP: c2
      LISTEN_TCP_PORT : 10057
      SEED_PORT_1600_TCP_ADDR: seed

